title: "The Canadian public service"
description: "A Montreal perspective"
  # theme: jekyll-theme-architect
show_downloads: false
github:
  is_project_page: false
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: "assets/PDF"
    values:
      PDF: true

plugins:
  - jekyll-datapage-generator

page_gen-dirs: true # uncomment, if you prefer to generate named folders

page_gen:
  - data: 'members'
    template: 'profile'
    name: 'full_name'
    dir: 'people'
